apiVersion: v1
kind: Pod
metadata:
  name: natter-test-pod
  labels:
    app: natter-test-pod
spec:
  containers:
  - name: natter-test
    image: k8s.gcr.io/test-webserver:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: natter-test-svc-nodeport-sctp
  annotations:
    nsx_nat_ip: "172.20.20.20"
    nsx_nat_router_name: nat-test
    nsx_nat_priority: "50" # Must be a string. K8s does not like ints!
    nsx_nat_service_prefix: sctp # If service doesn't exist it will be created <prefix>-<port number> for each port
  labels:
    app: natter-test-pod-0
spec:
  selector:
    app: natter-test-pod
  ports:
    - name: sctp-4000
      protocol: SCTP
      port: 4000
    - name: sctp-4001
      protocol: SCTP
      port: 4001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: natter-test-svc-nodeport-tcp
  annotations:
    nsx_nat_ip: "172.20.20.20"
    nsx_nat_router_name: nat-test
    nsx_nat_priority: "51" # Must be a string. K8s does not like ints!
    nsx_nat_service_prefix: tcp # If service doesn't exist it will be created <prefix>-<port number> for each port
  labels:
    app: natter-test-pod-0
spec:
  selector:
    app: natter-test-pod
  ports:
    - protocol: TCP
      port: 80
  type: NodePort